- name: Pull and run Docker image
  hosts: localhost
  tasks:
    # - name: List all K8s namespaces
    #   k8s_info:
    #     api_version: v1
    #     kind: Namespace
    #     kubeconfig: /home/runner/.kube/config
    #   register: namespaces

    - name: Create namespace webgoat if not exist
      kubernetes.core.k8s:
        name: webgoat
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy application
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: webgoat
            namespace: webgoat
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: webgoat
            template:
              metadata:
                labels:
                  app: webgoat
              spec:
                containers:
                  - name: webgoat
                    image: "jesusles/webgoat:main"
                    ports:
                      - containerPort: 8080  # This matches the port inside the container
                      - containerPort: 9090  # This is the second port inside the container

    - name: Create service to expose the application
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: webgoat
            namespace: webgoat
          spec:
            type: LoadBalancer  # Automatically create a LoadBalancer
            selector:
              app: webgoat  # Service will route traffic to pods with this label
            ports:
              - protocol: TCP
                port: 8080       # Expose this port on the service to the outside world
                targetPort: 8080  # Forward to containerPort 8080 inside the container

    # - name: Display namespaces
    #   debug:
    #     msg: "Namespace: {{ item.metadata.name }}"
    #   loop: "{{ namespaces.resources }}"
    # - name: Ensure Docker image is pulled
    #   docker_image:
    #     name: hello-world
    #     source: pull

    # - name: Run Docker container
    #   docker_container:
    #     name: hello-world-container
    #     image: hello-world
    #     state: started
    #     ports:
    #       - "8080:80"  # Example of mapping ports
