- name: Pull and run Docker image
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure Docker image is pulled
      docker_image:
        name: hello-world
        source: pull

    - name: Run Docker container
      docker_container:
        name: hello-world-container
        image: hello-world
        state: started
        ports:
          - "8080:80"  # Example of mapping ports
