global:
  scrape_interval: 15s # How often to scrape targets by default
  evaluation_interval: 15s # How often to evaluate rules
  scrape_timeout: 10s # Timeout for each scrape

alerting:
  alertmanagers:
    static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/config/alert_rules.yml"
  - alert_rules.yaml

server:
  extraVolumeMounts:
    - name: alert-rules-volume
      mountPath: /etc/prometheus/config
      subPath: alert_rules.yaml
  extraVolumes:
    - name: alert-rules-volume
      configMap:
        name: prometheus-alert-rules

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape WebGoat app
  - job_name: 'webgoat'
    static_configs:
      - targets: ['localhost:8080']

  # Scrape Kubernetes metrics from kube-state-metrics
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-stats-metrics:8080']
