name: Publish Docker image

on:
  push:
    branches:
      - dockerscan
      - releases/*

jobs:  
  build:
    name: Build and scan Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
            java-version: '21'
            distribution: 'temurin'

      - name: Build application
        run: mvn clean package

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: Dockerfile
          push: false # Do not push to Docker Hub yet
          tags: temporary-image:latest

  security_scan:
    name: Container Security Analysis
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub (optional, if private images are used)
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: temporary-image:latest
          severity: HIGH,CRITICAL
          format: table
          exit-code: 1 # Fail if vulnerabilities are found

      - name: Scan with Docker Scout
        run: docker scout cves temporary-image:latest

      - name: Scan with Clair
        uses: quay/clair-action@main
        with:
          image-ref: temporary-image:latest
          format: sarif
          output: clair_results.sarif
          docker-config-dir: /

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: clair_results.sarif
